### ISSUE TITLE
Row and Column sorting mixed up

### ISSUE THREAD

**Issue by BrainStone** [jsnimda/Inventory-Profiles#1]
When sorting in rows it sorts in columns and vice versa.

See these screenshots:

![2019-11-30_18 24 14](https://user-images.githubusercontent.com/4106544/69903791-b0314180-139e-11ea-9882-14555b8f3e99.png)
![2019-11-30_18 24 19](https://user-images.githubusercontent.com/4106544/69903792-b0314180-139e-11ea-8b5d-94c301bc21a2.png)

This is the Forge version.  
Forge: 28.1.93  
Inventory Profiles: 0.1.0-dev.5

**Comment by taz4hvn** [comment]
still true in 20w12a 0.2.0

**Comment by jsnimda** [comment]
"Sort in columns" means different types of items are arranged following the vertical direction, if there is not enough space, then it will breaks into two or three or more columns.
(For example: double chest has only 6 rows but you have 7 stacks of different items, then you can see there are two columns after doing "Sort in columns")
Same type of items are then in horizontal direction. So when there are a large amount of same item, it seems that row and column are mixed up but it is actually not.

**Comment by JackNUMBER** [comment]
@jsnimda It's misleading for me too, even I understand your naming way. You named the sort direction and with the icon we expect items alignement direction. I think it's the boundary between tech and UX  (how it works vs how it feels 🙂).

**Comment by jsnimda** [comment]
v0.3+ now you can interchange those two functions (if you want. `Gui Setttings -> Post Action`). icon and tooltip text are still not configurable though... (but you can change them via resourcepacks if you really want to)
