### ISSUE TITLE
Server kicks me out after creating a furnace

### ISSUE THREAD

**Issue by Strumero** [jsnimda/Inventory-Profiles#12]
[crash-2020-07-13_12.36.09-client.txt](https://github.com/jsnimda/Inventory-Profiles/files/4913509/crash-2020-07-13_12.36.09-client.txt)

**Comment by AtoxIO** [comment]
+1

**Comment by jsnimda** [comment]
It may not actually solve the issue, but now v0.4.1 should do nothing instead of crash. Report if you see any weird output.
