### ISSUE TITLE
Config GUI buttons "split" at higher resolutions

### ISSUE THREAD

**Issue by bermudalocket** [jsnimda/Inventory-Profiles#19]
Hi, I've come across an issue with the config GUI. I am on a 2019 MacBook Pro 16" which has a resolution of 3072 x 1920. When I have Minecraft open and maximized, the Inventory Profiles config buttons "split".

[Here's an image](https://i.imgur.com/jlpO6uQ.jpg) with Minecraft maximized. You can see all of the buttons along the right-hand side have split into two, but still act as one.

[Here's another image](https://i.imgur.com/vjOBBJv.jpeg) of the GUI after I decrease the size of the window by approximately 15%. You can see the first two buttons are still split but the rest have merged back into one.

**Comment by jsnimda** [comment]
Fixed in c47487b and 2e556d9
