### ISSUE TITLE
[Feature Request] Auto-refill

### ISSUE THREAD

**Issue by cbwang2016** [jsnimda/Inventory-Profiles#5]
It is well known that the original _Inventory-Tweaks_ mod has the "auto-refill" function...It's really useful, especially in a server.
Would you consider implement it in the future?

**Comment by JackNUMBER** [comment]
With _Profiles_ it's the must have feature!

**Comment by jsnimda** [comment]
Added in v0.3+ (feel free to submit any advancements for this function)
