### ISSUE TITLE
Please change the mod version on curseforge to 1.16.5 instead of 1.16.2

### ISSUE THREAD

**Issue by yuesha-yc** [jsnimda/Inventory-Profiles#59]
This will allow modpackers to add the mod

**Comment by blackd** [comment]
this mod is abandoned 
there is a fork that have full 1.16.5 and 1.17.x compatibility here https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next

**Comment by yuesha-yc** [comment]
> this mod is abandoned 
> 
> there is a fork that have full 1.16.5 and 1.17.x compatibility here https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next 

Does this have the entire feature of the original mod?

**Comment by blackd** [comment]
Since I forked this mode I've added number of new features.

But some of the "tweaks" were considered cheating by some servers and were moved in another mod https://github.com/blackd/sbt.
