### ISSUE TITLE
Hotkey only works for sort/open gui, not functioning for column/row/move all

### ISSUE THREAD

**Issue by Avera9eJoe** [jsnimda/Inventory-Profiles#8]
Greetings! I absolutely love this mod, although the hotkeys are not functioning for anything except for default sort or open gui.

To repeat: Open a single player or multiplayer game, open inventory, and press the hotkey to sort by column, row, or move all. Observe that nothing happens.

**Comment by jsnimda** [comment]
You can set the `Context` of `Advanced Keybind Settings` of those keys to `Gui` instead of `In-game`. They supposed to be `Gui` as default. I'll fix it in the next version.

**Comment by Avera9eJoe** [comment]
Ah, many thanks! With your info I set the keybinds to `Context: In-game/GUI` and `Allow extra keys: True` and everything works now. Many thanks! Closing this issue now :)

**Comment by jsnimda** [comment]
;)
